version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/DrSmithFr/go-console
    steps:
      - checkout

      - run: go get github.com/stretchr/testify/assert

      - run: go test -v ./tests/color/
      - run: go test -v ./tests/formatter/
      - run: go test -v ./tests/input/
      - run: go test -v ./tests/input/argument
      - run: go test -v ./tests/input/definition
      - run: go test -v ./tests/input/option
