version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.18
    working_directory: /go/src/github.com/DrSmithFr/go-console
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
      - run:
          name: Run tests
          command: go test -v ./...
